// <auto-generated />
using System;
using DepotContainer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepotContainer.Infrastructure.Migrations
{
    [DbContext(typeof(DepotDbContext))]
    [Migration("20251021040647_RemoveDepotIdFromBlock")]
    partial class RemoveDepotIdFromBlock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepotContainer.Domain.Entities.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<int>("BlockCapacity")
                        .HasColumnType("int")
                        .HasColumnName("block_capacity");

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("block_name");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit")
                        .HasColumnName("is_virtual");

                    b.Property<int>("MaxBays")
                        .HasColumnType("int")
                        .HasColumnName("max_bays");

                    b.Property<int>("MaxRows")
                        .HasColumnType("int")
                        .HasColumnName("max_rows");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("int")
                        .HasColumnName("max_tiers");

                    b.HasKey("BlockId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("booking_number");

                    b.Property<int?>("ContQuantity")
                        .HasColumnType("int")
                        .HasColumnName("cont_quantity");

                    b.Property<string>("ContSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cont_size");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("cus_id");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("operator_name");

                    b.Property<DateTime?>("ReleaseExpireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("release_expire_date");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Container", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cont_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerId"));

                    b.Property<string>("ContCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cont_condition");

                    b.Property<int?>("ContIsoId")
                        .HasColumnType("int")
                        .HasColumnName("cont_iso_id");

                    b.Property<string>("ContStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cont_status");

                    b.Property<string>("ContainerNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cont_no");

                    b.Property<DateTime?>("DateOfManufacture")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_manufacture");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit")
                        .HasColumnName("is_empty");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("operator_name");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_in");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_out");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("ContainerId");

                    b.HasIndex("ContIsoId");

                    b.HasIndex("SlotId");

                    b.ToTable("Container");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.HasKey("CategoryId");

                    b.ToTable("ContainerCategory");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerISO", b =>
                {
                    b.Property<int>("ContIsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cont_iso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContIsoId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<double?>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("iso_code");

                    b.Property<double?>("Length")
                        .HasColumnType("float")
                        .HasColumnName("length");

                    b.Property<double?>("MaximumWeight")
                        .HasColumnType("float")
                        .HasColumnName("maximum_weight");

                    b.Property<double?>("TareWeight")
                        .HasColumnType("float")
                        .HasColumnName("tare_weight");

                    b.Property<double?>("Width")
                        .HasColumnType("float")
                        .HasColumnName("width");

                    b.HasKey("ContIsoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ContainerISO");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerMovementHis", b =>
                {
                    b.Property<int>("HisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("his_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HisId"));

                    b.Property<int?>("ContId")
                        .HasColumnType("int")
                        .HasColumnName("cont_id");

                    b.Property<DateTime>("MoveAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("move_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("StatusHis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_his");

                    b.HasKey("HisId");

                    b.HasIndex("ContId");

                    b.HasIndex("SlotId");

                    b.HasIndex("StaffId");

                    b.ToTable("ContainerMovementHis");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cus_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tax_id");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.EIR", b =>
                {
                    b.Property<int>("EirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eir_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EirId"));

                    b.Property<int?>("BatNo")
                        .HasColumnType("int")
                        .HasColumnName("bat_no");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int?>("ContId")
                        .HasColumnType("int")
                        .HasColumnName("cont_id");

                    b.Property<int?>("CusId")
                        .HasColumnType("int")
                        .HasColumnName("cus_id");

                    b.Property<string>("EirNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EirNumber");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IssueDate");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("plate_number");

                    b.Property<DateTime>("RegisAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("regis_at");

                    b.Property<int?>("SealId")
                        .HasColumnType("int")
                        .HasColumnName("seal_id");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EirType");

                    b.HasKey("EirId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ContId");

                    b.HasIndex("CusId");

                    b.HasIndex("SealId");

                    b.HasIndex("StaffId");

                    b.ToTable("EIR");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Seal", b =>
                {
                    b.Property<int>("SealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SealId"));

                    b.Property<int>("ContId")
                        .HasColumnType("int")
                        .HasColumnName("cont_id");

                    b.Property<DateTime?>("SealAppliedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("seal_applied_at");

                    b.Property<string>("SealNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("seal_no");

                    b.Property<string>("SealOwner")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seal_owner");

                    b.Property<DateTime?>("SealRemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("seal_removed_at");

                    b.HasKey("SealId");

                    b.HasIndex("ContId");

                    b.ToTable("Seal");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("Bay")
                        .HasColumnType("int")
                        .HasColumnName("bay");

                    b.Property<int>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    b.Property<int>("Row")
                        .HasColumnType("int")
                        .HasColumnName("row");

                    b.Property<string>("StatusSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_slot");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.HasKey("SlotId");

                    b.HasIndex("BlockId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("staff_name");

                    b.Property<string>("StaffType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("staff_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("StaffId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Booking", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Container", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.ContainerISO", "ContIso")
                        .WithMany("Containers")
                        .HasForeignKey("ContIsoId");

                    b.HasOne("DepotContainer.Domain.Entities.Slot", "Slot")
                        .WithMany("Containers")
                        .HasForeignKey("SlotId");

                    b.Navigation("ContIso");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerISO", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.ContainerCategory", "Category")
                        .WithMany("ContainerISOs")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerMovementHis", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.Container", "Container")
                        .WithMany("ContainerMovementHis")
                        .HasForeignKey("ContId");

                    b.HasOne("DepotContainer.Domain.Entities.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId");

                    b.HasOne("DepotContainer.Domain.Entities.Staff", "Staff")
                        .WithMany("ContainerMovementHis")
                        .HasForeignKey("StaffId");

                    b.Navigation("Container");

                    b.Navigation("Slot");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.EIR", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.Booking", "Booking")
                        .WithMany("EIRs")
                        .HasForeignKey("BookingId");

                    b.HasOne("DepotContainer.Domain.Entities.Container", "Container")
                        .WithMany("EIRs")
                        .HasForeignKey("ContId");

                    b.HasOne("DepotContainer.Domain.Entities.Customer", "Customer")
                        .WithMany("EIRs")
                        .HasForeignKey("CusId");

                    b.HasOne("DepotContainer.Domain.Entities.Seal", "Seal")
                        .WithMany()
                        .HasForeignKey("SealId");

                    b.HasOne("DepotContainer.Domain.Entities.Staff", "Staff")
                        .WithMany("EIRs")
                        .HasForeignKey("StaffId");

                    b.Navigation("Booking");

                    b.Navigation("Container");

                    b.Navigation("Customer");

                    b.Navigation("Seal");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Seal", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.Container", "Container")
                        .WithMany("Seals")
                        .HasForeignKey("ContId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Slot", b =>
                {
                    b.HasOne("DepotContainer.Domain.Entities.Block", "Block")
                        .WithMany("Slots")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Block", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Booking", b =>
                {
                    b.Navigation("EIRs");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Container", b =>
                {
                    b.Navigation("ContainerMovementHis");

                    b.Navigation("EIRs");

                    b.Navigation("Seals");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerCategory", b =>
                {
                    b.Navigation("ContainerISOs");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.ContainerISO", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("EIRs");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("DepotContainer.Domain.Entities.Staff", b =>
                {
                    b.Navigation("ContainerMovementHis");

                    b.Navigation("EIRs");
                });
#pragma warning restore 612, 618
        }
    }
}
